version: '2'

services:

  proxy:
    image: daocloud.io/daocloud/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php7:
    # image: registry.cn-shenzhen.aliyuncs.com/xiaobe/php56
    build: ./
    ports:
      - '5050'
      - '80'
      - '8866:8866'
    volumes:
      - ~/Code/Dingzhi/common:/var/www/html
    environment:
      - VIRTUAL_HOST=ims.dev

  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

### Memcached Container #####################################

  memcached:
    build: ./memcached
    volumes:
      - ./memcached:/var/lib/memcached
    ports:
      - "11211:11211"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"